name: 機能要求 / Feature Request
description: 新しい機能の追加や既存機能の改善を提案する場合にご利用ください / Use this to suggest new features or improvements to existing functionality
title: "[Feature] "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        機能要求をありがとうございます。あなたのアイデアをお聞かせください！
        
        Thank you for your feature request. We'd love to hear your ideas!

  - type: textarea
    id: feature_summary
    attributes:
      label: 機能の概要 / Feature Summary
      description: 提案する機能を簡潔に説明してください / Briefly describe the proposed feature
      placeholder: |
        例：課題カードに優先度を色分けで表示する機能
        Example: Feature to display priority with color coding on issue cards
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: 動機・背景 / Motivation & Background
      description: なぜこの機能が必要だと思うか、どのような問題を解決したいかを説明してください / Explain why this feature is needed and what problem it would solve
      placeholder: |
        例：現在、課題の優先度がカード上で視覚的に分からないため、重要な課題を見落としやすい。色分けがあることで、一目で優先度を判断できるようになる。
        Example: Currently, issue priority is not visually apparent on cards, making it easy to overlook important issues. Color coding would allow instant priority recognition.
    validations:
      required: true

  - type: textarea
    id: detailed_description
    attributes:
      label: 詳細な説明 / Detailed Description
      description: 機能の動作方法や実装のイメージを詳しく説明してください / Describe how the feature should work and your implementation ideas
      placeholder: |
        例：
        - 高優先度：赤色の境界線
        - 中優先度：黄色の境界線  
        - 低優先度：青色の境界線
        - 設定画面で色分け表示のON/OFFを切り替え可能
        - 既存のBacklogの優先度設定と連動
        
        Example:
        - High priority: Red border
        - Medium priority: Yellow border
        - Low priority: Blue border
        - Toggle color coding ON/OFF in settings
        - Integrate with existing Backlog priority settings
    validations:
      required: true

  - type: dropdown
    id: feature_type
    attributes:
      label: 機能の種類 / Feature Type
      description: どのような種類の機能要求かを選択してください / Select what type of feature request this is
      options:
        - "新機能の追加 / New feature addition"
        - "既存機能の改善 / Existing feature improvement"
        - "UI/UXの改善 / UI/UX improvement"
        - "パフォーマンスの改善 / Performance improvement"
        - "アクセシビリティの改善 / Accessibility improvement"
        - "設定オプションの追加 / Additional setting options"
        - "その他 / Other"
    validations:
      required: true

  - type: dropdown
    id: target_feature
    attributes:
      label: 対象機能 / Target Feature
      description: 新機能または改善対象の機能を選択してください / Select the new or target feature for improvement
      options:
        - "ボードアコーディオン機能 / Board Accordion Feature"
        - "ショートカットキー表示機能 / Shortcut Key Display Feature"
        - "課題Pending機能 / Issue Pending Feature"
        - "課題コメントURLコピー機能 / Comment URL Copy Feature"
        - "設定画面 / Settings Screen"
        - "新機能 / New feature"
        - "その他 / Other"
    validations:
      required: true

  - type: textarea
    id: use_cases
    attributes:
      label: 使用場面・シナリオ / Use Cases & Scenarios
      description: この機能をどのような場面で使用するかを具体的に説明してください / Describe specific scenarios where this feature would be used
      placeholder: |
        例：
        1. 大量の課題がある大規模プロジェクトで、緊急度の高い課題を素早く特定したい
        2. チームメンバーが課題の優先度を一目で把握して、適切な作業順序を決めたい
        3. プロジェクトマネージャーが全体の優先度バランスを視覚的に確認したい
        
        Example:
        1. In large projects with many issues, quickly identify high-urgency issues
        2. Team members instantly understand issue priority to determine proper work order
        3. Project managers visually confirm overall priority balance
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 要求の優先度 / Request Priority
      description: この機能要求の優先度を選択してください / Select the priority of this feature request
      options:
        - "高 / High - 日常的に困っている問題を解決する / Solves daily problems"
        - "中 / Medium - あると便利な機能 / Nice to have feature"
        - "低 / Low - 将来的にあると良い機能 / Future enhancement"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 代替案 / Alternatives
      description: 現在この問題をどのように解決しているか、または検討した他の解決方法があれば記載してください / How are you currently solving this problem, or any other solutions you've considered
      placeholder: |
        例：現在は課題詳細を個別に開いて優先度を確認しているが、時間がかかる
        Example: Currently opening individual issue details to check priority, but it's time-consuming

  - type: textarea
    id: additional_context
    attributes:
      label: 追加情報 / Additional Context
      description: その他、機能実装に役立つ情報や参考資料があれば記載してください / Any other information or references that might help with feature implementation
      placeholder: |
        - 参考になるWebサイトやツール / Reference websites or tools
        - モックアップやスケッチ / Mockups or sketches
        - 類似機能を持つ他のツール / Other tools with similar features

  - type: checkboxes
    id: checklist
    attributes:
      label: 確認事項 / Checklist
      description: 以下の項目を確認してください / Please check the following items
      options:
        - label: 既存のIssueで同様の機能要求がないか検索した / Searched for similar feature requests in existing issues
          required: true
        - label: この機能が既存の機能と重複しないことを確認した / Confirmed this feature doesn't duplicate existing functionality
          required: true
        - label: 機能の必要性と実装方法を具体的に説明した / Provided specific explanation of feature necessity and implementation approach
          required: true